name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: |
          echo "version=$(grep 'Version:' ./woo-shiprocket-shipping/woo-shiprocket-shipping.php | cut -d ':' -f 2 | tr -d ' ')" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FA_PRO_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            Changes in this release:
            - ... (list your changes here) ...
          draft: false
          prerelease: false

      - name: Zip the plugin
        run: zip -r woo-shiprocket-shipping.zip woo-shiprocket-shipping/ -x *.git* *.github*

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FA_PRO_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./woo-shiprocket-shipping.zip
          asset_name: woo-shiprocket-shipping.zip
          asset_content_type: application/zip