name: Update update-info.json

on:
  # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update update-info.json
        run: |
          # Fetch the latest version from woo-shiprocket-shipping.php
          version=$(grep 'Version:' ./woo-shiprocket-shipping/woo-shiprocket-shipping.php | cut -d ':' -f 2 | tr -d ' ')
          
          # Construct the download URL (replace with your actual URL format)
          download_url="https://github.com/ProgrammerNomad/woo-shiprocket-shipping/releases/download/$version/woo-shiprocket-shipping.zip" 
          
          # Create the JSON content for update-info.json
          cat << EOF > ./update-info.json
          {
            "version": "$version",
            "download_url": "$download_url",
            "sections": {
              "description": "This is the latest version of the Font Awesome Pro plugin.",
              "changelog": "Updated plugin features and bug fixes.",
              "commit_version": "$(git rev-parse HEAD)"
            }
          }
          EOF

      - name: Commit Changes
        run: |
          git config --global user.name 'ProgrammerNomad'
          git config --global user.email 'shiv@srapsware.com'
          git add .
          git commit -m "Update update-info.json"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main